title: Isabel Costa
author: Isabel Costa
email: isabel.monteiro.costa@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  I’m a Software Developer from Portugal. 
  I like working on Open Source every since 
  I participated as a student on Google Summer of Code program. 
  I enjoy software development, watching movie reviews, 
  being with my family, idem idem ...

# social links
twitter_username: isabelcmdcosta
github_username:  isabelcosta
linkedin_username: isabelcmdcosta
medium_username: isabelcmdcosta
devto_username: isabelcmdcosta
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

google_analytics: UA-110733190-1

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - blog.md
 - work.md
 - talks.md
 - contact.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
